"""add enabled_assistants to chat model

Revision ID: 1d1e65841b1c
Revises: f48d36d4cbd5
Create Date: 2025-11-12 09:56:52.467076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d1e65841b1c'
down_revision = 'f48d36d4cbd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs', if_exists=True)
    op.drop_table('apscheduler_jobs', if_exists=True)

    # Add column as nullable first, set default, then make non-nullable
    op.add_column('chats', sa.Column('enabled_assistants', sa.JSON(), nullable=True))
    op.execute("UPDATE chats SET enabled_assistants = '[]'::json WHERE enabled_assistants IS NULL")
    op.alter_column('chats', 'enabled_assistants', nullable=False)

    # Skip inbox_id change - this was from previous migration drift
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emails', 'inbox_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_column('chats', 'enabled_assistants')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###