"""initial_schema

Revision ID: 4887dfb7d6ac
Revises:
Create Date: 2026-01-13 21:44:35.330134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.models.base import GUID

# revision identifiers, used by Alembic.
revision = '4887dfb7d6ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email_domain', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('managed_by', sa.Text(), nullable=True),
    sa.Column('config_name', sa.Text(), nullable=True),
    sa.Column('config_checksum', sa.Text(), nullable=True),
    sa.Column('external_group_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_email_domain'), 'groups', ['email_domain'], unique=False)
    op.create_index(op.f('ix_groups_external_group_id'), 'groups', ['external_group_id'], unique=True)
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=True)
    op.create_table('llm_providers',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('api_endpoint', sa.String(length=500), nullable=True),
    sa.Column('default_model', sa.String(length=100), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('managed_by', sa.Text(), nullable=True),
    sa.Column('config_name', sa.Text(), nullable=True),
    sa.Column('config_checksum', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('otp_sessions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_sessions_email'), 'otp_sessions', ['email'], unique=False)
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('managed_by', sa.Text(), nullable=True),
    sa.Column('config_name', sa.Text(), nullable=True),
    sa.Column('config_checksum', sa.Text(), nullable=True),
    sa.Column('external_user_id', sa.String(length=255), nullable=True),
    sa.Column('external_metadata', sa.JSON(), nullable=True),
    sa.Column('last_external_sync', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_external_user_id'), 'users', ['external_user_id'], unique=True)
    op.create_index(op.f('ix_users_last_login_at'), 'users', ['last_login_at'], unique=False)
    op.create_table('agents',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=True),
    sa.Column('group_id', GUID(), nullable=True),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('llm_provider_id', GUID(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=False),
    sa.Column('initial_messages', sa.JSON(), nullable=True),
    sa.Column('enabled_functions', sa.JSON(), nullable=False),
    sa.Column('enabled_mcp_tools', sa.JSON(), nullable=False),
    sa.Column('enabled_agents', sa.JSON(), nullable=False),
    sa.Column('function_parameters', sa.JSON(), nullable=False),
    sa.Column('mcp_tool_parameters', sa.JSON(), nullable=False),
    sa.Column('state_namespaces_readonly', sa.JSON(), nullable=False),
    sa.Column('state_namespaces_readwrite', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('managed_by', sa.Text(), nullable=True),
    sa.Column('config_name', sa.Text(), nullable=True),
    sa.Column('config_checksum', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['llm_provider_id'], ['llm_providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'name', name='uix_agent_namespace_name')
    )
    op.create_index(op.f('ix_agents_group_id'), 'agents', ['group_id'], unique=False)
    op.create_index(op.f('ix_agents_llm_provider_id'), 'agents', ['llm_provider_id'], unique=False)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=False)
    op.create_index(op.f('ix_agents_namespace'), 'agents', ['namespace'], unique=False)
    op.create_index(op.f('ix_agents_user_id'), 'agents', ['user_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('functions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('group_id', GUID(), nullable=True),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('enabled_namespaces', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('managed_by', sa.Text(), nullable=True),
    sa.Column('config_name', sa.Text(), nullable=True),
    sa.Column('config_checksum', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'name', name='uix_function_namespace_name')
    )
    op.create_index(op.f('ix_functions_group_id'), 'functions', ['group_id'], unique=False)
    op.create_index(op.f('ix_functions_name'), 'functions', ['name'], unique=False)
    op.create_index(op.f('ix_functions_namespace'), 'functions', ['namespace'], unique=False)
    op.create_index(op.f('ix_functions_user_id'), 'functions', ['user_id'], unique=False)
    op.create_table('group_members',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('group_id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('added_by', GUID(), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['removed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_members_group_id'), 'group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_members_user_id'), 'group_members', ['user_id'], unique=False)
    op.create_table('group_permissions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('group_id', GUID(), nullable=False),
    sa.Column('permission_key', sa.String(length=255), nullable=False),
    sa.Column('permission_value', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_group_permission_unique', 'group_permissions', ['group_id', 'permission_key'], unique=True)
    op.create_index(op.f('ix_group_permissions_group_id'), 'group_permissions', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_permissions_permission_key'), 'group_permissions', ['permission_key'], unique=False)
    op.create_table('installed_packages',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('installed_by', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['installed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'package_name', name='uix_package_user_name')
    )
    op.create_index(op.f('ix_installed_packages_package_name'), 'installed_packages', ['package_name'], unique=False)
    op.create_index(op.f('ix_installed_packages_user_id'), 'installed_packages', ['user_id'], unique=False)
    op.create_table('mcp_servers',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('group_id', GUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_connected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('managed_by', sa.Text(), nullable=True),
    sa.Column('config_name', sa.Text(), nullable=True),
    sa.Column('config_checksum', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_servers_group_id'), 'mcp_servers', ['group_id'], unique=False)
    op.create_index(op.f('ix_mcp_servers_name'), 'mcp_servers', ['name'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_is_revoked'), 'refresh_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_token_prefix'), 'refresh_tokens', ['token_prefix'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('scheduled_jobs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('group_id', GUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('function_namespace', sa.String(length=255), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cron_expression', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uix_schedule_user_name')
    )
    op.create_index(op.f('ix_scheduled_jobs_group_id'), 'scheduled_jobs', ['group_id'], unique=False)
    op.create_index(op.f('ix_scheduled_jobs_name'), 'scheduled_jobs', ['name'], unique=True)
    op.create_index(op.f('ix_scheduled_jobs_user_id'), 'scheduled_jobs', ['user_id'], unique=False)
    op.create_table('states',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('group_id', GUID(), nullable=True),
    sa.Column('namespace', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_states_expires_at', 'states', ['expires_at'], unique=False)
    op.create_index(op.f('ix_states_group_id'), 'states', ['group_id'], unique=False)
    op.create_index(op.f('ix_states_key'), 'states', ['key'], unique=False)
    op.create_index(op.f('ix_states_namespace'), 'states', ['namespace'], unique=False)
    op.create_index('ix_states_namespace_visibility', 'states', ['namespace', 'visibility'], unique=False)
    op.create_index(op.f('ix_states_user_id'), 'states', ['user_id'], unique=False)
    op.create_index(op.f('ix_states_visibility'), 'states', ['visibility'], unique=False)
    op.create_index('uq_state_user_namespace_key', 'states', ['user_id', 'namespace', 'key'], unique=True)
    op.create_table('webhooks',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('group_id', GUID(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('function_namespace', sa.String(length=255), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('http_method', sa.Enum('GET', 'POST', 'PUT', 'DELETE', 'PATCH', name='httpmethod'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_values', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('managed_by', sa.Text(), nullable=True),
    sa.Column('config_name', sa.Text(), nullable=True),
    sa.Column('config_checksum', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path', 'http_method', name='uix_webhook_path_method')
    )
    op.create_index(op.f('ix_webhooks_group_id'), 'webhooks', ['group_id'], unique=False)
    op.create_index(op.f('ix_webhooks_path'), 'webhooks', ['path'], unique=True)
    op.create_index(op.f('ix_webhooks_user_id'), 'webhooks', ['user_id'], unique=False)
    op.create_table('chats',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('group_id', GUID(), nullable=True),
    sa.Column('agent_id', GUID(), nullable=True),
    sa.Column('agent_namespace', sa.String(length=255), nullable=True),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('chat_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_agent_id'), 'chats', ['agent_id'], unique=False)
    op.create_index(op.f('ix_chats_group_id'), 'chats', ['group_id'], unique=False)
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_table('function_versions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('function_id', GUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_function_versions_function_id'), 'function_versions', ['function_id'], unique=False)
    op.create_table('executions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('execution_id', sa.String(length=255), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('trigger_type', sa.Enum('WEBHOOK', 'SCHEDULE', name='triggertype'), nullable=False),
    sa.Column('trigger_id', sa.String(length=255), nullable=False),
    sa.Column('chat_id', GUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'AWAITING_INPUT', 'COMPLETED', 'FAILED', name='executionstatus'), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('generator_state', sa.LargeBinary(), nullable=True),
    sa.Column('input_prompt', sa.Text(), nullable=True),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_chat_id'), 'executions', ['chat_id'], unique=False)
    op.create_index(op.f('ix_executions_execution_id'), 'executions', ['execution_id'], unique=True)
    op.create_index(op.f('ix_executions_function_name'), 'executions', ['function_name'], unique=False)
    op.create_index(op.f('ix_executions_user_id'), 'executions', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('chat_id', GUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('enabled_functions', sa.JSON(), nullable=True),
    sa.Column('enabled_mcp_tools', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_table('step_executions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('execution_id', sa.String(length=255), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'AWAITING_INPUT', 'COMPLETED', 'FAILED', name='executionstatus'), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.execution_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_executions_execution_id'), 'step_executions', ['execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_step_executions_execution_id'), table_name='step_executions')
    op.drop_table('step_executions')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_executions_user_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_function_name'), table_name='executions')
    op.drop_index(op.f('ix_executions_execution_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_chat_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_function_versions_function_id'), table_name='function_versions')
    op.drop_table('function_versions')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_group_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_agent_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_webhooks_user_id'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_path'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_group_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index('uq_state_user_namespace_key', table_name='states')
    op.drop_index(op.f('ix_states_visibility'), table_name='states')
    op.drop_index(op.f('ix_states_user_id'), table_name='states')
    op.drop_index('ix_states_namespace_visibility', table_name='states')
    op.drop_index(op.f('ix_states_namespace'), table_name='states')
    op.drop_index(op.f('ix_states_key'), table_name='states')
    op.drop_index(op.f('ix_states_group_id'), table_name='states')
    op.drop_index('ix_states_expires_at', table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_scheduled_jobs_user_id'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_name'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_group_id'), table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_prefix'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_mcp_servers_name'), table_name='mcp_servers')
    op.drop_index(op.f('ix_mcp_servers_group_id'), table_name='mcp_servers')
    op.drop_table('mcp_servers')
    op.drop_index(op.f('ix_installed_packages_user_id'), table_name='installed_packages')
    op.drop_index(op.f('ix_installed_packages_package_name'), table_name='installed_packages')
    op.drop_table('installed_packages')
    op.drop_index(op.f('ix_group_permissions_permission_key'), table_name='group_permissions')
    op.drop_index(op.f('ix_group_permissions_group_id'), table_name='group_permissions')
    op.drop_index('ix_group_permission_unique', table_name='group_permissions')
    op.drop_table('group_permissions')
    op.drop_index(op.f('ix_group_members_user_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_group_id'), table_name='group_members')
    op.drop_table('group_members')
    op.drop_index(op.f('ix_functions_user_id'), table_name='functions')
    op.drop_index(op.f('ix_functions_namespace'), table_name='functions')
    op.drop_index(op.f('ix_functions_name'), table_name='functions')
    op.drop_index(op.f('ix_functions_group_id'), table_name='functions')
    op.drop_table('functions')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_agents_user_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_namespace'), table_name='agents')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_llm_provider_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_group_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_last_login_at'), table_name='users')
    op.drop_index(op.f('ix_users_external_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otp_sessions_email'), table_name='otp_sessions')
    op.drop_table('otp_sessions')
    op.drop_table('llm_providers')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_index(op.f('ix_groups_external_group_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_email_domain'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###