"""add enabled_assistants to assistant model

Revision ID: f48d36d4cbd5
Revises: 77a4ae1faf22
Create Date: 2025-11-12 09:55:46.930659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f48d36d4cbd5'
down_revision = '77a4ae1faf22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs', if_exists=True)
    op.drop_table('apscheduler_jobs', if_exists=True)

    # Add column as nullable first, set default, then make non-nullable
    op.add_column('assistants', sa.Column('enabled_assistants', sa.JSON(), nullable=True))
    op.execute("UPDATE assistants SET enabled_assistants = '[]'::json WHERE enabled_assistants IS NULL")
    op.alter_column('assistants', 'enabled_assistants', nullable=False)

    # Skip inbox_id change - this was from previous migration drift
    # op.alter_column('emails', 'inbox_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emails', 'inbox_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_column('assistants', 'enabled_assistants')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###