"""add namespace and ownership to templates

Revision ID: 255094362009
Revises: 902ee53babf8
Create Date: 2026-01-26 12:25:37.970237

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "255094362009"
down_revision = "902ee53babf8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: APScheduler manages its own tables - removed drop operations
    op.drop_index(op.f("ix_installed_packages_package_name"), table_name="installed_packages")
    op.create_index(
        op.f("ix_installed_packages_package_name"),
        "installed_packages",
        ["package_name"],
        unique=True,
    )
    op.drop_constraint(
        op.f("pending_tool_approvals_message_id_fkey"), "pending_tool_approvals", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("pending_tool_approvals_user_id_fkey"), "pending_tool_approvals", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("pending_tool_approvals_chat_id_fkey"), "pending_tool_approvals", type_="foreignkey"
    )
    op.create_foreign_key(None, "pending_tool_approvals", "messages", ["message_id"], ["id"])
    op.create_foreign_key(None, "pending_tool_approvals", "chats", ["chat_id"], ["id"])
    op.create_foreign_key(None, "pending_tool_approvals", "users", ["user_id"], ["id"])
    # Add namespace column as nullable first
    op.add_column("templates", sa.Column("namespace", sa.String(length=255), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE templates SET namespace = 'default' WHERE namespace IS NULL")
    # Now make it NOT NULL
    op.alter_column("templates", "namespace", nullable=False)

    op.add_column("templates", sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column("templates", sa.Column("group_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint(op.f("uix_template_name"), "templates", type_="unique")
    op.drop_index(op.f("ix_templates_name"), table_name="templates")
    op.create_index(op.f("ix_templates_name"), "templates", ["name"], unique=False)
    op.create_index(op.f("ix_templates_group_id"), "templates", ["group_id"], unique=False)
    op.create_index(op.f("ix_templates_namespace"), "templates", ["namespace"], unique=False)
    op.create_index(op.f("ix_templates_user_id"), "templates", ["user_id"], unique=False)
    op.create_unique_constraint("uix_template_namespace_name", "templates", ["namespace", "name"])
    op.create_foreign_key(None, "templates", "groups", ["group_id"], ["id"])
    op.create_foreign_key(None, "templates", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "templates", type_="foreignkey")
    op.drop_constraint(None, "templates", type_="foreignkey")
    op.drop_constraint("uix_template_namespace_name", "templates", type_="unique")
    op.drop_index(op.f("ix_templates_user_id"), table_name="templates")
    op.drop_index(op.f("ix_templates_namespace"), table_name="templates")
    op.drop_index(op.f("ix_templates_group_id"), table_name="templates")
    op.drop_index(op.f("ix_templates_name"), table_name="templates")
    op.create_index(op.f("ix_templates_name"), "templates", ["name"], unique=True)
    op.create_unique_constraint(
        op.f("uix_template_name"), "templates", ["name"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("templates", "group_id")
    op.drop_column("templates", "user_id")
    op.drop_column("templates", "namespace")
    op.drop_constraint(None, "pending_tool_approvals", type_="foreignkey")
    op.drop_constraint(None, "pending_tool_approvals", type_="foreignkey")
    op.drop_constraint(None, "pending_tool_approvals", type_="foreignkey")
    op.create_foreign_key(
        op.f("pending_tool_approvals_chat_id_fkey"),
        "pending_tool_approvals",
        "chats",
        ["chat_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("pending_tool_approvals_user_id_fkey"),
        "pending_tool_approvals",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("pending_tool_approvals_message_id_fkey"),
        "pending_tool_approvals",
        "messages",
        ["message_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_installed_packages_package_name"), table_name="installed_packages")
    op.create_index(
        op.f("ix_installed_packages_package_name"),
        "installed_packages",
        ["package_name"],
        unique=False,
    )
    # Note: APScheduler manages its own tables - removed create operations
    # ### end Alembic commands ###
