"""add skills table and agent enabled_skills

Revision ID: 54056f649874
Revises: 20260131_states
Create Date: 2026-02-01 15:52:39.024093

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "54056f649874"
down_revision = "20260131_states"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skills",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("namespace", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace", "name", name="uq_skill_namespace_name"),
    )
    op.create_index(op.f("ix_skills_name"), "skills", ["name"], unique=False)
    op.create_index(op.f("ix_skills_namespace"), "skills", ["namespace"], unique=False)
    op.create_index(op.f("ix_skills_user_id"), "skills", ["user_id"], unique=False)
    # Note: APScheduler manages its own tables - removed drop operations
    # Add enabled_skills column with default value for existing rows
    op.add_column(
        "agents", sa.Column("enabled_skills", sa.JSON(), server_default="[]", nullable=False)
    )
    op.drop_constraint(op.f("executions_chat_id_fkey"), "executions", type_="foreignkey")
    op.create_foreign_key(None, "executions", "chats", ["chat_id"], ["id"])
    op.drop_constraint(op.f("messages_chat_id_fkey"), "messages", type_="foreignkey")
    op.create_foreign_key(None, "messages", "chats", ["chat_id"], ["id"])
    op.drop_constraint(
        op.f("pending_tool_approvals_chat_id_fkey"), "pending_tool_approvals", type_="foreignkey"
    )
    op.create_foreign_key(None, "pending_tool_approvals", "chats", ["chat_id"], ["id"])
    op.drop_column("user_roles", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_roles", sa.Column("role", sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "pending_tool_approvals", type_="foreignkey")
    op.create_foreign_key(
        op.f("pending_tool_approvals_chat_id_fkey"),
        "pending_tool_approvals",
        "chats",
        ["chat_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.create_foreign_key(
        op.f("messages_chat_id_fkey"), "messages", "chats", ["chat_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(None, "executions", type_="foreignkey")
    op.create_foreign_key(
        op.f("executions_chat_id_fkey"),
        "executions",
        "chats",
        ["chat_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("agents", "enabled_skills")
    # Note: APScheduler manages its own tables - removed create operations
    op.drop_index(op.f("ix_skills_user_id"), table_name="skills")
    op.drop_index(op.f("ix_skills_namespace"), table_name="skills")
    op.drop_index(op.f("ix_skills_name"), table_name="skills")
    op.drop_table("skills")
    # ### end Alembic commands ###
